---
- name: ansible playbook to copy a file
  hosts: webserver
  become: true
  tasks:
  - name: ensure apache is installed and up to date
    apt:
      name: apache2
      state: present

  - name: write the apache config file 
    copy:  
      src:  000-default.conf
      dest: /etc/apache2/sites-available/000-default.conf
    notify: Restart apache2
  - name: apache is running (and enable it at boot)
    service: name=apache2 state=started enabled=yes

  handlers:
  - name: Restart apache2
    service: name=apache2 state=restarted
      
